services:
  - type: web
    name: desafio-blog
    env: ruby
    region: ohio
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production} & (sleep 10 && bundle exec sidekiq -C config/sidekiq.yml)"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: desafio-blog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: desafio-blog
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: desafio-blog
    region: ohio
    plan: free
    
services:
  - type: redis
    name: desafio-blog
    region: ohio
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []