services:
  - type: web
    name: desafio-blog
    env: ruby
    region: ohio
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: desafio-blog
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: desafio-blog
          property: connectionString
    healthCheckPath: /
    autoDeploy: true

  - type: redis
    name: desafio-blog
    region: ohio
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: worker
    name: desafio-blog-worker
    env: ruby
    region: ohio
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -L log/sidekiq.log -e production -C config/sidekiq.yml
    autoDeploy: false
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: desafio-blog
          property: connectionString

databases:
  - name: desafio-blog
    region: ohio
    plan: free
